# Generated by Django 5.0.3 on 2024-03-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Train_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Train_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('start_station_code', models.CharField(max_length=20)),
                ('End_station_code', models.CharField(max_length=20)),
            ],
        ),
    ]
